---
# echo 'y' | mkfs.gfs2 -j3 -p lock_dlm -t pcs_cluster:gfs2 /dev/cluster_vg/cluster_lv
# echo 'y' | mkfs.gfs2 -j3 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv
- name: Create a gfs2 filesystem on /dev/mapper/device and check disk blocks
  ansible.builtin.shell: "echo 'y' | mkfs.gfs2 -j2 -p lock_dlm -t {{ cluster_name }}:gfs2-{{ item.fsname }} {{ item.lv }}"
  with_items: 
    - { lv: '/dev/web_vg/web_lv', fsname: 'web' }

- name: Wait a little
  pause:
    seconds: 5
