---
# vgcreate --shared cluster_vg /dev/mapper/device
- name: Create a volume groups
  community.general.lvg:
    #state: present
    vg: "{{ item.vg }}"
    pvs: "{{ item.pv }}"
    #vg_options: "-Ay -cy" # "--autobackup y --clustered y"
    vg_options: "--shared"
  with_items: 
    - { vg: 'web_cluster_vg', pv: '/dev/mapper/webpath' }
  when: "ansible_hostname in 'backend-01'"

- name: Wait a little
  pause:
    seconds: 5

# vgchange --lockstart cluster_vg
- name: start lock manager for shared
  ansible.builtin.command: "vgchange --lockstart {{ item.vg }}"
  with_items: 
    - { vg: 'web_cluster_vg' }
  when: "ansible_hostname in ['backend-02','backend-03']"

# lvcreate --activate sy -l 100%FREE -n cluster_lv cluster_vg
- name: Create a logical volumes
  community.general.lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    size: "{{ item.size }}"
    opts: --activate sy
  with_items: 
    - { vg: 'web_cluster_vg', lv: 'web_cluster_lv', size: '100%FREE' }
  when: "ansible_hostname in 'backend-01'"

- name: Wait a little
  pause:
    seconds: 5