---
# mpathconf --enable --with_multipathd y
- name: Setup multipath in PCS Servers
  ansible.builtin.command: mpathconf --enable --with_multipathd y

# /usr/lib/udev/scsi_id --whitelisted --replace-whitespace --device=/dev/vdb
- name: Get ID device /dev/sda
  ansible.builtin.command: /usr/lib/udev/scsi_id --whitelisted --replace-whitespace --device=/dev/vdb
  register: scsi_id_vdb

#- name: Info scsi_id all iscsi devices
#  ansible.builtin.debug:
#    msg:
#      - "{{ scsi_id_vdb.stdout }}"

# cp /src/multipath.conf.j2 /etc/multipath.conf
- name: Copy multipath config file
  ansible.builtin.template:
    src: multipath/multipath.conf.j2
    dest: /etc/multipath.conf

# multipath -a /dev/device
- name: Add devices to multipath
  ansible.builtin.command: "multipath -a {{ item }}"
  with_items:
    - /dev/vdb

# multipath -r
- name: Reload multipath
  ansible.builtin.command: multipath -r

# systemctl restart multipathd
- name: "Enable and Start Multipathd Service"
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
    enabled: true